export const catalogoEndal = [
  { id: 1, nombre: "ENVASE REDONDO PARA TAPA", referencia: "2800", imagen: "" },
  { id: 2, nombre: "ENVASE REDONDO PARA TAPA", referencia: "2935", imagen: "" },
  { id: 3, nombre: "ENVASE REDONDO PARA TAPA", referencia: "21400", imagen: "21400.jpg" },
  { id: 4, nombre: "ENVASE REDONDO PARA TAPA", referencia: "21425", imagen: "21425.jpg" },
  { id: 5, nombre: "ENVASE REDONDO PARA TAPA", referencia: "21900", imagen: "21900.jpg" },
  { id: 6, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4280", imagen: "rectstapa4280.jpg" },
  { id: 7, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4360", imagen: "" },
  { id: 8, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "44965", imagen: "44965.jpg" },
  { id: 9, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4425", imagen: "4425.jpg" },
  { id: 10, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4465", imagen: "4465.jpg" },
  { id: 11, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4470", imagen: "4470.jpg" },
  { id: 12, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4590", imagen: "4590.jpg" },
  { id: 13, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4750", imagen: "4750.jpg" },
  { id: 14, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4797", imagen: "4797.jpg" },
  { id: 15, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4835", imagen: "4835.jpg" },
  { id: 16, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "4860", imagen: "4860.jpg" },
  { id: 17, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "41500", imagen: "41500.jpg" },
  { id: 18, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "42200", imagen: "42200.jpg" },
  { id: 19, nombre: "ENVASE RECTANGULAR SIN TAPA", referencia: "42400", imagen: "42400.jpg" },
  { id: 20, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5250", imagen: "5250.jpg" },
  { id: 21, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5360", imagen: "5360.jpg" },
  { id: 22, nombre: "PORTA ROLLO", referencia: "Porta Rollo Film", imagen: "portarollos sin tapa.jpg" },
  { id: 23, nombre: "PORTA ROLLO", referencia: "Porta Rollo Aluminio", imagen: "portarollos con tapa.jpg" },
  { id: 24, nombre: "MÁQUINA", referencia: "M21400", imagen: "m21400.jpg" },
  { id: 25, nombre: "MAQUINA", referencia: "M42600", imagen: "M42600.jpg" },
  { id: 26, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5475", imagen: "5475.jpg" },
  { id: 27, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5580", imagen: "5580.jpg" },
  { id: 28, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5590", imagen: "5590.jpg" },
  { id: 29, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5860", imagen: "5860.jpg" },
  { id: 30, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "5890", imagen: "5890.jpg" },
  { id: 31, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "51180", imagen: "51180.jpg" },
  { id: 32, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "51500", imagen: "51500.jpg" },
  { id: 33, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "52200", imagen: "52200.jpg" },
  { id: 34, nombre: "ENVASE RECTANGULAR PARA TAPA", referencia: "52400", imagen: "52400.jpg" },
  { id: 35, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1205", imagen: "1205.jpg" },
  { id: 36, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1230", imagen: "1230.jpg" },
  { id: 37, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1240", imagen: "1240.jpg" },
  { id: 38, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1250", imagen: "1250.jpg" },
  { id: 39, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1280", imagen: "1280.jpg" },
  { id: 40, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1375", imagen: "1375.jpg" },
  { id: 41, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1790", imagen: "1790.jpg" },
  { id: 42, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1900", imagen: "1900.jpg" },
  { id: 43, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1935", imagen: "1935.jpg" },
  { id: 44, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1975", imagen: "1975.jpg" },
  { id: 45, nombre: "ENVASE REDONDO SIN TAPA", referencia: "11100", imagen: "11100.jpg" },
  { id: 46, nombre: "ENVASE REDONDO SIN TAPA", referencia: "11103", imagen: "11103.jpg" },
  { id: 47, nombre: "ENVASE REDONDO SIN TAPA", referencia: "11150", imagen: "" },
  { id: 48, nombre: "ENVASE REDONDO SIN TAPA", referencia: "1470", imagen: "" },
  { id: 49, nombre: "OVALADAS", referencia: "41230V", imagen: "41230V.jpg" },
  { id: 50, nombre: "OVALADAS", referencia: "750870", imagen: "750870.jpg" },
  { id: 51, nombre: "OVALADAS", referencia: "751650", imagen: "751650.jpg" },
  { id: 52, nombre: "OVALADAS", referencia: "752151", imagen: "752151.jpg" },
  { id: 53, nombre: "OVALADAS", referencia: "CONCHA", imagen: "CONCHA.jpg" },
  { id: 54, nombre: "ENVASES OVALADOS PARA TAPA", referencia: "41900", imagen: "41900.jpg" },
  { id: 55, nombre: "ENVASES OVALADOS PARA TAPA", referencia: "42600", imagen: "42600.jpg" },
  { id: 56, nombre: "BAÑERAS", referencia: "53114", imagen: "53114.jpg" },
  { id: 57, nombre: "BAÑERAS", referencia: "53535", imagen: "53535.jpg" },
  { id: 58, nombre: "BAÑERAS", referencia: "53680", imagen: "53680.jpg" },
  { id: 59, nombre: "BAÑERAS", referencia: "53885", imagen: "53885.jpg" },
  { id: 60, nombre: "BOMBONERÍA", referencia: "1/87", imagen: "1-87 bomboneria.jpg" },
  { id: 61, nombre: "BOMBONERÍA", referencia: "2/86", imagen: "bomboneria aluminio 2-86.jpg" },
  { id: 62, nombre: "BOMBONERÍA", referencia: "3/87", imagen: "bomboneria aluminio 3-87.jpg" },
  { id: 63, nombre: "BOMBONERÍA", referencia: "3102", imagen: "bomboneria aluminio 3102.jpg" },
  { id: 64, nombre: "BOMBONERÍA", referencia: "4/86", imagen: "bomboneria aluminio 4-86.jpg" },
  { id: 65, nombre: "BOMBONERÍA", referencia: "7/87", imagen: "bomboneria aluminio 7-87.jpg" },
  { id: 66, nombre: "BOMBONERÍA", referencia: "8/96", imagen: "8-96.jpg" },
  { id: 67, nombre: "BOMBONERÍA", referencia: "9/89", imagen: "9-89.jpg" },
  { id: 68, nombre: "BOMBONERÍA", referencia: "ORO2", imagen: "oro2.jpg" },
  { id: 69, nombre: "BOMBONERÍA", referencia: "1/87A", imagen: "" },
  { id: 70, nombre: "BOMBONERÍA", referencia: "2/86A", imagen: "" },
  { id: 71, nombre: "BOMBONERÍA", referencia: "3/87A", imagen: "" },
  { id: 72, nombre: "BOMBONERÍA", referencia: "C2/86", imagen: "c2-86.jpg" },
  { id: 73, nombre: "BOMBONERÍA", referencia: "C3/89", imagen: "c3-89.jpg" },
  { id: 74, nombre: "BOMBONERÍA", referencia: "C4/89", imagen: "c4-89.jpg" },
  { id: 75, nombre: "BOMBONERÍA", referencia: "C5/95", imagen: "c5-95.jpg" },
  { id: 76, nombre: "BOMBONERÍA", referencia: "CORNE", imagen: "corne.jpg" },
  { id: 77, nombre: "BOMBONERÍA", referencia: "C10/95", imagen: "c10-95.jpg" },
  { id: 78, nombre: "BOMBONERÍA", referencia: "CA1/95", imagen: "ca1-95.jpg" },
  { id: 79, nombre: "PASTELERÍA", referencia: "1025", imagen: "1025.jpg" },
  { id: 80, nombre: "PASTELERÍA", referencia: "1030", imagen: "1030.jpg" },
  { id: 81, nombre: "PASTELERÍA", referencia: "1052", imagen: "1052.jpg" },
  { id: 82, nombre: "PASTELERÍA", referencia: "1060", imagen: "1060.jpg" },
  { id: 83, nombre: "PASTELERÍA", referencia: "1070", imagen: "1070.jpg" },
  { id: 84, nombre: "PASTELERÍA", referencia: "1080", imagen: "1080.jpg" },
  { id: 85, nombre: "PASTELERÍA", referencia: "1090", imagen: "1090.jpg" },
  { id: 86, nombre: "PASTELERÍA", referencia: "1101", imagen: "1101.jpg" },
  { id: 87, nombre: "PASTELERÍA", referencia: "1103", imagen: "1103.jpg" },
  { id: 88, nombre: "PASTELERÍA", referencia: "1127", imagen: "1127.jpg" },
  { id: 89, nombre: "PASTELERÍA", referencia: "4037", imagen: "4037.jpg" },
  { id: 90, nombre: "PASTELERÍA", referencia: "5/86", imagen: "5-86.jpg" },
  { id: 91, nombre: "PASTELERÍA", referencia: "T1127", imagen: "t1127.jpg" },
  { id: 92, nombre: "PASTELERÍA", referencia: "4037A", imagen: "4037a.jpg" },
  { id: 93, nombre: "PASTELERÍA", referencia: "T1103", imagen: "t1103.jpg" },
  { id: 94, nombre: "PARED LISA", referencia: "1135-pl", imagen: "1135pl.jpg" },
  { id: 95, nombre: "PARED LISA", referencia: "1140-pl", imagen: "1140pl.jpg" },
  { id: 96, nombre: "PARED LISA", referencia: "4117-pl", imagen: "4117pl.jpg" },
  { id: 97, nombre: "PARED LISA", referencia: "4330-pl", imagen: "4330pl.jpg" },
  { id: 98, nombre: "PARED LISA", referencia: "1040-pla", imagen: "1040pla.jpg" },
  { id: 99, nombre: "PARED LISA", referencia: "T4330-pla", imagen: "4330pla.jpg" },
  { id: 101, nombre: "ALUMINIO INDUSTRIAL", referencia: "Alum. Industrial", imagen: "aluminio industrial.jpg" },
  { id: 102, nombre: "ALUMINIO INDUSTRIAL", referencia: "Aluminio Industrial 40 cm", imagen: "aluminio industrial.jpg" },
  { id: 103, nombre: "BOBINA FILM INDUSTRIAL", referencia: "Film Industrial 40", imagen: "film industrial.jpg" },
  { id: 104, nombre: "ENVASE OPS OVALADO", referencia: "End-500", imagen: "end 250.jpg" },
  { id: 105, nombre: "ENVASE OPS OVALADO", referencia: "End 750", imagen: "end375.jpg" },
  { id: 106, nombre: "ENVASE OPS OVALADO", referencia: "END 600", imagen: "envase ops ovalado.jpg" },
  { id: 108, nombre: "ENVASE OPS OVALADO", referencia: "END 1000", imagen: "end 1000.jpg" },
  { id: 109, nombre: "ENVASE OPS OVALADO", referencia: "END 1500", imagen: "end1 500.jpg" },
  { id: 110, nombre: "ENVASE OPS OVALADO", referencia: "END 2000", imagen: "end 2500.jpg" },
  { id: 111, nombre: "ENVASE OPS OVALADO", referencia: "ENS 600 Ensaladera", imagen: "ensaladera ops.jpg" },
  { id: 112, nombre: "ENVASE OPS CUADRADO", referencia: "END1 250", imagen: "end1 250.jpg" },
  { id: 113, nombre: "ENVASE OPS CUADRADO", referencia: "END1 375", imagen: "end1 375.jpg" },
  { id: 114, nombre: "ENVASE OPS CUADRADO", referencia: "END1 500", imagen: "end1 500.jpg" },
  { id: 115, nombre: "ENVASE OPS CUADRADO", referencia: "END1 670", imagen: "end1 670.jpg" },
  { id: 116, nombre: "ENVASE OPS CUADRADO", referencia: "END1 750", imagen: "end1 750.jpg" },
  { id: 117, nombre: "ENVASE OPS CUADRADO", referencia: "END1 1000", imagen: "end1 1000.jpg" },
  { id: 118, nombre: "ENVASE OPS CUADRADO", referencia: "END1 2000", imagen: "end1 2000.jpg" },
  { id: 119, nombre: "ENVASE OPS CUADRADO", referencia: "END1 1500", imagen: "end1 1500.jpg" },
  { id: 120, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "1103T", imagen: "t1103.jpg" },
  { id: 123, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T1140", imagen: "t1140.jpg" },
  { id: 124, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T1250", imagen: "t1250.jpg" },
  { id: 125, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T1280", imagen: "t1280.jpg" },
  { id: 126, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T2800", imagen: "t2800.jpg" },
  { id: 127, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T2935", imagen: "t2935.jpg" },
  { id: 128, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T5250", imagen: "t5250.jpg" },
  { id: 129, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T5360", imagen: "t5360.jpg" },
  { id: 130, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-5475", imagen: "t5475.jpg" },
  { id: 131, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-5580", imagen: "t5580.jpg" },
  { id: 132, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-5590", imagen: "t5590.jpg" },
  { id: 133, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-5860", imagen: "t5860.jpg" },
  { id: 138, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-21900", imagen: "t21900.jpg" },
  { id: 139, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-51180", imagen: "t5180.jpg" },
  { id: 140, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-51500", imagen: "t51500.jpg" },
  { id: 141, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-52200", imagen: "t52200.jpg" },
  { id: 142, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-52400", imagen: "t52400.jpg" },
  { id: 143, nombre: "TAPAS ENVASES REDONDOS Y RECTANGULARES", referencia: "T-1135", imagen: "t1135.jpg" },
  { id: 145, nombre: "BOBINA DE PAPEL VEGETAL", referencia: "Rollo Vegetal 15", imagen: "" },
  { id: 146, nombre: "BOBINA PAPEL VEGETAL", referencia: "Rollo Vegetal 8", imagen: "" },
  { id: 147, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "11103-P", imagen: "" },
  { id: 148, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "Plumcake", imagen: "" },
  { id: 149, nombre: "BOBINA FILM DOMÉSTICO", referencia: "Rollo PF", imagen: "" },
  { id: 150, nombre: "BOBINA FILM DOMÉSTICO", referencia: "Rollo Film", imagen: "" },
  { id: 152, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "mini", imagen: "" },
  { id: 153, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "1375-PH", imagen: "" },
  { id: 154, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "cuadrado", imagen: "" },
  { id: 155, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "mini plumcake", imagen: "" },
  { id: 156, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "Tarta", imagen: "" },
  { id: 157, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "11150-PH", imagen: "" },
  { id: 158, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "plum bandeja", imagen: "" },
  { id: 159, nombre: "BOBINA ALUMINIO DOMÉSTICO", referencia: "8 metros", imagen: "aluminio domestico.jpg" },
  { id: 160, nombre: "BOBINA ALUMINIO DOMÉSTICO", referencia: "16 metros", imagen: "aluminio domestico.jpg" },
  { id: 161, nombre: "BOBINA ALUMINIO DOMÉSTICO", referencia: "50 metros", imagen: "aluminio domestico.jpg" },
  { id: 162, nombre: "BOBINA ALUMINIO DOMÉSTICO", referencia: "30 metros", imagen: "aluminio domestico.jpg" },
  { id: 163, nombre: "BOBINA FILM INDUSTRIAL", referencia: "Film industrial 30", imagen: "film industrial.jpg" },
  { id: 167, nombre: "ENVASE POLIPROPILENO PP", referencia: "END PP 500", imagen: "" },
  { id: 168, nombre: "ENVASE POLIPROPILENO PP", referencia: "END PP 750", imagen: "" },
  { id: 169, nombre: "ENVASE POLIPROPILENO PP", referencia: "END PP 1000", imagen: "" },
  { id: 170, nombre: "ENVASE POLIPROPILENO PP", referencia: "END PP 1500", imagen: "" },
  { id: 172, nombre: "ENVASE DE PAPEL PARA HORNEAR", referencia: "11103-PH", imagen: "" },
  { id: 174, nombre: "ENVASE 4590 PH", referencia: "4590-ph", imagen: "" },
];